### ISSUE TITLE
Homebridge file "accessories/cachedAccessories" need to be deleted sometimes

### ISSUE THREAD

**Issue by g88704** [NickChristensen/homebridge-unifi-block-clients#1]
Hello,

thanks for your great homebridge plugin. One thing I noticed (but maybe it depends on my homebridge docker installation) is the following:

- if I change the unifiBlockClients configuration, e.g. add another MAC-address
- Then the next homebridge restart results in an exception within the unifiBlockClients plugin

To solve this, i do the following right now:
- Stop the homebridge docker container
- Delete the file "accessories/cachedAccessories"
- Restart and everything is working like before

Is this normal or do I something wrong?

Thanks again and Kind Regards

Michael

**Comment by NickChristensen** [comment]
Hey Michael, thanks for the details. I'll take a look!

**Comment by redbug26** [comment]
Same error :(
Message is "Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory"

**Comment by NickChristensen** [comment]
I haven't taken the time to dig into this, but I'd love a pull request if someone understands how Homebridge accessory caching is supposed to work.

**Comment by NickChristensen** [comment]
Use https://github.com/homebridge/homebridge-plugin-template/blob/master/src/platform.ts as reference

**Comment by LEDLondon** [comment]
I get this error, i suspect due to unifi site two step verification as the username is correct: 28/06/2020, 23:28:52 HOOBS listening on port 8080.
28/06/2020, 23:28:54 Loaded plugin "homebridge-unifi-block-clients".
28/06/2020, 23:28:54 [unifiBlockClients] username is required. Check config.json.
28/06/2020, 23:28:54 Error
    at requiredConfig (/home/hoobs/.hoobs/node_modules/homebridge-unifi-block-clients/dist/index.js:120:13)
    at new Platform (/home/hoobs/.hoobs/node_modules/homebridge-unifi-block-clients/dist/index.js:124:50)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
28/06/2020, 23:28:54 Got SIGTERM, shutting down Bridge...

**Comment by rasgeek** [comment]
Hey , it stopes unblocking client how do i fix
