### ISSUE TITLE
ERROR: TypeError Cannot read property

### ISSUE THREAD

**Issue by suxus-zz** [NickChristensen/homebridge-unifi-block-clients#7]
Hello

I have currently this problem when i run your plugin. I have a Unifi DreamMachine Pro and i will control my AppleTV.

`
(node:8979) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
    at /usr/local/lib/node_modules/homebridge-unifi-block-clients/dist/index.js:156:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
`

My config.json looks like this
`
        {
            "platform": "unifiBlockClients",
            "name": "Unifi Block Clients",
            "username": "USER-FROM-WEBGUI",
            "password": "PASS-FROM-WEBGUI",
            "controllerUrl": "https://192.168.88.1",
            "clients": [
                "90:dd:5d:a5:65:3c"
            ]
        }`

Have you a idea whats my problem? Is it purhaps a problem that i have a UDM?

regards

**Comment by Zinski** [comment]
same issue with a cloud key gen2. I guess it has to do with the latest Firmware

**Comment by suxus-zz** [comment]
Check [this](https://github.com/plainsane/homebridge-unifi-kids-cry/issues/9)
